/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package web.powerpoint.slide.service;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import org.apache.poi.xslf.usermodel.XMLSlideShow;
import org.apache.poi.xslf.usermodel.XSLFComment;
import org.apache.poi.xslf.usermodel.XSLFSlide;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;
import web.google.slide.GoogleHelper;
import web.google.slide.SlidesData;
import web.model.Contact;

import web.model.WizardData;
import web.page.targetmarketingpage.TargetMarketingHeaderRow;
import web.powerpoint.slide.SlideDataHelper;
import web.powerpoint.slide.SlideInterface;

import web.repository.WizardDataRepository;
import web.repository.WizardRepository;

/**
 *
 * @author andrewhinton
 *
 *
 * import java.util.Arrays; import java.util.List; import
 * java.util.stream.Collectors;
 *
 * public class ListFilterExample { public static void main(String[] args) {
 * List<Product> allProducts = Arrays.asList( new Product("Laptop", 1200.0), new
 * Product("Mouse", 25.0), new Product("Keyboard", 75.0), new Product("Monitor",
 * 300.0) );
 *
 * // Filter products with price > 100 List<Product> expensiveProducts =
 * allProducts.stream() .filter(product -> product.getPrice() > 100.0)
 * .collect(Collectors.toList());
 *
 * System.out.println("Expensive Products:"); expensiveProducts.forEach(product
 * -> System.out.println(product.getName())); } }
 *
 */
@Service
public class PowerPointServiceImpl implements PowerPointService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private WizardRepository wizardRepository;
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private WizardDataRepository wizardDataRepository;
    private static final Logger mLog = LoggerFactory.getLogger(PowerPointServiceImpl.class.getName());
    @Value("classpath:powerpointtemplate/tv.pptx")
    Resource resourceFileTV;

    @Value("classpath:powerpointtemplate/tv.pptx")
    Resource resourceFileRadio;
    @Value("${powerpoint.download.folder}")

    String powerpointdownloadfolderpath;

    private String getSlidePageName(XSLFSlide slide) {
        String pageName = null;
        pageName = slide.getSlideName();
        List<XSLFComment> comments = slide.getComments();
        for (XSLFComment comment : comments) {
            pageName = comment.getText();
            mLog.info("Slide page name " + pageName);
            break;

        }
        return pageName;
    }

    private void removeSlides(XMLSlideShow ppt, List<SlideInterface> slidesModels) {
        SlidesData slidesData = slidesModels.getFirst().getmSlidesData();
        TargetMarketingHeaderRow targetMarketingHeaderRow = slidesData.getPageModels().getTargetMarketingHeaderRow();
        String status = targetMarketingHeaderRow.getRowStatus();
        //Want26to35ToWant36to45 5 THIS on
        if (status.equals("Want26to35ToWant36to45")) {
            List<Integer> indicesToRemove = Arrays.asList(6, 7, 8, 9); // Example indices
            Collections.sort(indicesToRemove, Collections.reverseOrder());

            for (int index : indicesToRemove) {
                ppt.removeSlide(index);
            }

        }

        //6  (6,7,8,9,10)
        if (status.equals("Want36to45ToWant46to55")) {

            List<Integer> indicesToRemove = Arrays.asList(5, 7, 8, 9); // Example indices
            Collections.sort(indicesToRemove, Collections.reverseOrder());

            for (int index : indicesToRemove) {
                ppt.removeSlide(index);
            }

        }

        //Want46to55ToWant55Plus 7
        if (status.equals("Want46to55ToWant55Plus")) {
            List<Integer> indicesToRemove = Arrays.asList(5, 6, 8, 9); // Example indices
            Collections.sort(indicesToRemove, Collections.reverseOrder());

            for (int index : indicesToRemove) {
                ppt.removeSlide(index);
            }
        }
        //8
        if (status.equals("Want19to25ToWant26to35")) {
            List<Integer> indicesToRemove = Arrays.asList(5, 6, 7, 9); // Example indices
            Collections.sort(indicesToRemove, Collections.reverseOrder());

            for (int index : indicesToRemove) {
                ppt.removeSlide(index);
            }

        }

        //slide 9 needs to remain
        if (status.equals("Want12to18ToWant19to25")) {
            List<Integer> indicesToRemove = Arrays.asList(5, 6, 7, 8); // Example indices
            Collections.sort(indicesToRemove, Collections.reverseOrder());

            for (int index : indicesToRemove) {
                ppt.removeSlide(index);
            }

        }

        /*
           Want12to18ToWant19to25 10
           Want19to25ToWant26to35 9
           
           Want36to45ToWant46to55 7
          
         */
    }

    @Override
    public String buildPowerPointDocument(int wizardId, Contact contact) {
        //wizardRepository.
        //Optional<Wizard> wizardOpt = wizardRepository.findById(id);
        //Wizard wizard = wizardOpt.orElse(null);
        Iterable<WizardData> dataPages = wizardDataRepository.findByWizardid(Integer.valueOf(wizardId));
        List<String> excludedPagesList = GoogleHelper.getSlidesExcluded(dataPages);
        List<SlideInterface> slidesModels = SlideDataHelper.getSlidesData(dataPages);

        try {
            // wizard.
            InputStream fis = readTemplate(contact.getClientType());
            org.apache.poi.openxml4j.util.ZipSecureFile.setMinInflateRatio(0.001); // or a different value as needed

            XMLSlideShow ppt = new XMLSlideShow(fis);
            fis.close();
            removeSlides(ppt, slidesModels);

            for (XSLFSlide slide : ppt.getSlides()) {
                String slidePageName = slide.getSlideName();
                mLog.info("Slide number " + slidePageName);
                // String slidePageName = getSlidePageName(slide);
                mLog.info("slidePageName " + slidePageName);
//                if (slidePageName == null || slidePageName.isEmpty()) {
//                    mLog.info("Slide number skipped - not comment added" + slidePageName);
//                    continue;
//                }
                //skip if no page def
                // Filter products with price > 100
                SlideInterface foundmodel = SlideDataHelper.findModelBySlidePageName(slidePageName, slidesModels);
                if (foundmodel != null) {
                    foundmodel.populateSlide(slide);
                } else {

                    mLog.info("Error  on slide " + slidePageName);
                    continue;
                }

            }
            String contactname = contact.getName();
            contactname = contactname.replaceAll("\\s+", "");

            String filepath = "/opt/wizard/download/" + contactname + ".pptx";

            File myObj = new File(filepath);
            if (myObj.createNewFile()) {
                mLog.info("File created: " + myObj.getName());
            } else {
                mLog.info("File already exists.");
            }
            String finalPath = filepath.replace(".pptx", "_updated.pptx");
            // Write the changes to a new file
            FileOutputStream out = new FileOutputStream(finalPath);
            //System.out.println("file path " + powerpointdownloadfolderpath);

            ppt.write(out);
            out.close();

            String downloadFileName = contactname + "_updated.pptx";

            mLog.info("file path " + filepath);
            return downloadFileName;

        } catch (IOException ex) {
            mLog.equals(ex);
        }

        return "";
    }

    @Override
    public InputStream readTemplate(String clientType) throws IOException {
        if (clientType.equals("TV")) {
            String fileName = resourceFileTV.getFilename();

            mLog.info(fileName);
            return resourceFileTV.getInputStream();

        } else {

            String fileName = resourceFileRadio.getFilename();
            mLog.info(fileName);
            return resourceFileRadio.getInputStream();
        }

    }

}
