package web.google.slide;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.Environment;
import org.springframework.ui.Model;

import com.google.api.client.googleapis.auth.oauth2.GoogleIdToken;
import com.google.api.client.googleapis.auth.oauth2.GoogleTokenResponse;
import com.google.api.services.drive.Drive;
import com.google.api.services.drive.model.Comment;
import com.google.api.services.drive.model.CommentList;
import com.google.api.services.drive.model.File;
import com.google.api.services.slides.v1.model.BatchUpdatePresentationRequest;
import com.google.api.services.slides.v1.model.Request;

import web.google.slide.pages.EightConfidentialClientEvaluationOneSlide;
import web.google.slide.pages.EightConfidentialClientEvaluationOneTextSlide;
import web.google.slide.pages.FiveStrategicMarketingPageSlide;
import web.google.slide.pages.FourClientObjectiveSlide;
import web.google.slide.pages.FourClientObjectiveTextSlide;
import web.google.slide.pages.NineConfidentialClientEvaluationProposedSlide;
import web.google.slide.pages.NineConfidentialClientEvaluationProposedTextSlide;
import web.google.slide.pages.NineteenPlanAProposedTextSlide;
import web.google.slide.pages.OnePresentedToSlide;
import web.google.slide.pages.SevenConfidentialClientEvaluationTextSlide;
import web.google.slide.pages.SeventeenPlanAMediaSlide;
import web.google.slide.pages.SixTargetMarketingSlide;
import web.google.slide.pages.ThirtyPlanBSpreadSheetSlide;
import web.google.slide.pages.ThirtyPlanBSpreadSheetTextSlide;
import web.google.slide.pages.ThreeMarketPlaceCompetitionSlide;
import web.google.slide.pages.TwentyEightPlanBDigitalROICalculatorTextSlide;
import web.google.slide.pages.TwentyFivePlanBProposedTextSlide;
import web.google.slide.pages.TwentyNinePlanASpreadSheetSlide;
import web.google.slide.pages.TwentyNinePlanASpreadSheetTextSlide;
import web.google.slide.pages.TwentyPlanABEPTextSlide;
import web.google.slide.pages.TwentySevenPlanBLifetimeValuedTextSlide;
import web.google.slide.pages.TwentyOnePlanALifetimeValuedTextSlide;
import web.google.slide.pages.TwentySixPlanBBEPTextSlide;
import web.google.slide.pages.TwentyThreePlanBMediaSlide;
import web.google.slide.pages.TwentyTwoPlanADigitalROICalculatorTextSlide;
import web.google.slide.pages.TwoTeamCommitmentSlide;
import web.model.Wizard;
import web.model.WizardData;
import web.page.ChartBuilder;
import web.page.JSONManager;
import web.page.PageNameEnum;
import web.page.PieChart;
import web.page.Publish;
import web.page.PublishController;
import web.page.clientobjectivesonepage.ClientObjectivesOnePageModel;
import web.page.clientobjectivesonepage.ClientObjectivesOnePageTwoModel;
import web.page.clientobjectivesonepage.ClientObjectivesPageHelper;
import web.page.confidentialclientevaluationnonepage.ConfidentialClientEvaluationOnePageModel;
import web.page.extra.ExtraPageModel;
import web.page.marketplacecompetitionpage.MarketPlaceCompetitionPageModel;
import web.page.planABEPPage.PlanABEPPageModel;
import web.page.planBBEPPage.PlanBBEPPageModel;
import web.page.planDigitalroicalculatorpage.PlanDigitalROICalculatorPageModel;
import web.page.planalifetimevaluedpage.PlanALifetimeValuedPageModel;
import web.page.planamedipage.MediaChart;
import web.page.planamedipage.MediaChartHelper;
import web.page.planamedipage.PlanMediaPageModel;
import web.page.planbLifetimevaluedpage.PlanBLifetimeValuedPageModel;
import web.page.planproposedpage.PlanProposedPageModel;
import web.page.presentedtopage.PresentedToPageModel;
import web.page.strategicmarketingpageone.StrategicMarketingPageOneModel;
import web.page.strategicmarketingpagethree.StrategicMarketingHelper;
import web.page.strategicmarketingpagethree.StrategicMarketingPageThreeModel;
import web.page.strategicmarketingpagetwo.StrategicMarketingPageTwoModel;
import web.page.targetmarketingpage.TargetMarketingHeaderRow;
import web.page.targetmarketingpage.TargetMarketingPageModel;
import web.page.teamcommitmentpage.TeamCommitmentPageModel;
import web.repository.WizardDataRepository;
import web.repository.WizardRepository;
import web.util.EncryptionDecryptionManager;
import web.util.EnvUtil;

/**
 * @author andrewhinton
 *
 */
public class GoogleHelper {
	private static final Logger mLog = LoggerFactory.getLogger(GoogleHelper.class.getName());
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WizardDataRepository wizardDataRepository;
	@Autowired

	private Environment env;

	// inject it,
	@Autowired
	private EnvUtil envUtil;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WizardRepository wizardRepository;

	private List<Request> mRequests = new ArrayList<Request>();
    
	/**
	 * 
	 * @param mediaChart
	 * @return
	 */
	public static List<Object> writeJan(MediaChart mediaChart) throws Exception {
		if (mediaChart.getJanColor() == null) {
			mLog.error("null Jan data");
			throw new Exception("null Jan data");

		}
		List<Object> dataRowJan = new ArrayList<>();
		dataRowJan.add("Jan");
		String janColor = mediaChart.getJanColor();
		switch (janColor) {
		case "green":
			dataRowJan.add(mediaChart.getJan());
			dataRowJan.add(0);
			dataRowJan.add(0);
			break;
		case "red":
			dataRowJan.add(0);
			dataRowJan.add(mediaChart.getJan());
			dataRowJan.add(0);
			break;
		case "blue":
			dataRowJan.add(0);
			dataRowJan.add(0);
			dataRowJan.add(mediaChart.getJan());
			break;
		}
		return dataRowJan;

	}

	/**
	 * 
	 * @param mediaChart
	 * @return
	 * @throws Exception
	 */
	public static List<Object> writeFeb(MediaChart mediaChart) throws Exception {
		if (mediaChart.getFebColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Feb");
		String color = mediaChart.getFebColor();
		switch (color) {
		case "green":
			dataRow.add(mediaChart.getFeb());
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(mediaChart.getFeb());
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(mediaChart.getFeb());
			break;
		}
		return dataRow;

	}

	public static List<Object> writeMar(MediaChart mediaChart) throws Exception {
		if (mediaChart.getMarColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Mar");
		String color = mediaChart.getMarColor();
		int value = mediaChart.getMar();
		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	public static List<Object> writeApr(MediaChart mediaChart) throws Exception {
		if (mediaChart.getAprColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Apr");
		String color = mediaChart.getAprColor();
		int value = mediaChart.getApr();

		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	public static List<Object> writeMay(MediaChart mediaChart) throws Exception {
		if (mediaChart.getMayColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("May");
		String color = mediaChart.getMayColor();
		int value = mediaChart.getMay();
		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	public static List<Object> writeJun(MediaChart mediaChart) throws Exception {
		if (mediaChart.getJunColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Jun");
		String color = mediaChart.getJunColor();
		int value = mediaChart.getJun();
		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	public static List<Object> writeJul(MediaChart mediaChart) throws Exception {
		if (mediaChart.getJulColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Jul");
		String color = mediaChart.getJulColor();
		int value = mediaChart.getJul();
		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	public static List<Object> writeAug(MediaChart mediaChart) throws Exception {
		if (mediaChart.getAugColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Aug");
		String color = mediaChart.getAugColor();
		int value = mediaChart.getAug();
		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	public static List<Object> writeSep(MediaChart mediaChart) throws Exception {
		if (mediaChart.getSepColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Sep");
		String color = mediaChart.getSepColor();
		int value = mediaChart.getSep();
		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	public static List<Object> writeOct(MediaChart mediaChart) throws Exception {
		if (mediaChart.getOctColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Oct");
		String color = mediaChart.getOctColor();
		int value = mediaChart.getOct();
		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	public static List<Object> writeNov(MediaChart mediaChart) throws Exception {
		if (mediaChart.getNovColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Nov");
		String color = mediaChart.getNovColor();
		int value = mediaChart.getNov();
		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	public static List<Object> writeDec(MediaChart mediaChart) throws Exception {
		if (mediaChart.getDecColor() == null) {
			mLog.error("null data");
			throw new Exception("null data");

		}
		List<Object> dataRow = new ArrayList<>();
		dataRow.add("Dec");
		String color = mediaChart.getDecColor();
		int value = mediaChart.getDec();
		switch (color) {
		case "green":
			dataRow.add(value);
			dataRow.add(0);
			dataRow.add(0);
			break;
		case "red":
			dataRow.add(0);
			dataRow.add(value);
			dataRow.add(0);
			break;
		case "blue":
			dataRow.add(0);
			dataRow.add(0);
			dataRow.add(value);
			break;
		}
		return dataRow;

	}

	/**
	 * 
	 * @param tokenResponse
	 * @return Get logon email address
	 */
	public static String emailAddress(GoogleTokenResponse tokenResponse) {
		String email = null;
		try {
			GoogleIdToken idToken = tokenResponse.parseIdToken();
			GoogleIdToken.Payload payload = idToken.getPayload();
			email = payload.getEmail();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			mLog.error(e.getMessage());
		}
		//
		// String userId = payload.getSubject(); // Use this value as a key to identify
		// a user.
		// mLog.info("userId " + userId);
		// String email = payload.getEmail();
		return email;
	}

	/**
	 * Retrieve a list of comments.
	 *
	 * @param service Drive API service instance.
	 * @param fileId  ID of the file to retrieve comments for.
	 * @return List of comments.
	 * @throws RetrieveCommentsException
	 */
	public static Map<String, String> retrieveComments(Drive service, String fileId) throws RetrieveCommentsException {
		mLog.trace(GoogleSlideController.class.getName(), "retrieveComments");
		mLog.warn("entering retrieveComments");
		CommentList comments;

		Map<String, String> slides = new HashMap<String, String>();

		// fileId = "gb1e46e2962_1_0";
		mLog.info("retreiveComments start fileId [" + fileId + "]");
		try {
			comments = service.comments().list(fileId).setFields("*").execute();
			mLog.info("after service.comments().list(fileId).setFields(\"*\").execute()");
			// service.comments().list(fileId).
			List<Comment> commentList = comments.getComments();
			mLog.info("commentList  [" + commentList.size() + "]");
			for (Comment comment : commentList) {
				String desc = comment.getContent();
				mLog.info("desc [" + desc + "]");

				String[] pageNameAndPageId = desc.split("\\.");

				mLog.info("pageNameAndPageId length [" + pageNameAndPageId.length + "]");
				if (pageNameAndPageId != null && pageNameAndPageId.length > 0) {
					slides.put(pageNameAndPageId[0], pageNameAndPageId[1]);
					mLog.info("pagename [" + pageNameAndPageId[0] + "]");
					mLog.info("pageId [" + pageNameAndPageId[1] + "]");
				}

			}
			mLog.trace(GoogleSlideController.class.getName(), "retrieveComments");
			mLog.warn("exiting retrieveComments");
			return slides;
		} catch (IOException e) {

			mLog.error("error " + e.getMessage());
			mLog.warn("exiting retrieveComments");
			throw new RetrieveCommentsException(e.getMessage());
		}
	}

	/**
	 * 
	 * @return today date
	 */
	public static String getDateTime() {
		SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd 'at' HH:mm:ss z");
		Date date = new Date(System.currentTimeMillis());
		return formatter.format(date);
	}

	static HashMap<String, String> map = new HashMap<String, String>();

	static {
		if (map.isEmpty()) {

			map.put("introduceNewDepartmentLabel", "Introduce New Department/Products/Services");
			map.put("featureSpecificProductsLabel", "Feature Specific Products/Services");
			map.put("callAttentiontoBrandsPrivateLabelsCarriedLabel",
					"Call Attention to Brands/Private Labels Carried");
			map.put("promoteOffPriceItemsServicesLabel", "Promote Off-price Items/Services");
			map.put("quarterlySeasonalCampaignLabel", "Establish a quarterly spike/seasonal campaign");
			map.put("utilizeCoopVendorDollarsLabel", "Utilize Co-op/Vendor Dollars");
			map.put("retainCurrentConsumersLabel", "Retain/Recapture Consumers");
			map.put("increaseCustomerVisitsLabel", "Increase Frequency of Customer Visits");
			map.put("increaseTrafficLeadCallsLabel", "Grow New Traffic/Lead Calls");
			map.put("expandTargetConsumersLabel", "Expand Target Consumers (by age, sex, geography)");
			map.put("changeConsumerAttitudesLabel", "Change Consumer Attitudes");

			map.put("makePromotionalEventsStrongerLabel", "Make PromotionalEvents Stronger");
			map.put("increaseDigitalMobileOnlineResponseLabel", "Develop Digital/Mobile/Social Strategies");
			map.put("developDatabaseMarketingLabel", "Develop Database Marketing (Email and Text)");
			map.put("initiateCauseMarketingProgramLabel", "Initiate Cause Marketing Programs");
			map.put("developSpeciallyStagedEventLabel", "Develop Specially Staged Events");
			map.put("maintainMarketDominanceLabel", "Maintain Market Dominance");
			map.put("improveBusinessNameBrandLabel", "Elevate Business Brand/Image");
			map.put("establishorReestablishBusinessImageLabel", "Improve Reputation and Listing Management");
			map.put("createPentUpDemandLabel", "Enhance Website (Mobile, Response, SEO,SEM)");
			map.put("increaseMarketShareLabel", "Increase Market Share");
			map.put("otherLabel", "Other:");

		}

	}

	public static String convertStringToCurrency(String currency) {

		try {
			mLog.info("amount " + currency);
			double amount = Double.parseDouble(currency);
			NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("en", "US"));
			nf.setMaximumFractionDigits(0);
			String output = nf.format(amount);
			return output;
		} catch (Exception ex) {
			mLog.error("ERROR converting " + ex.getMessage());
			return currency;
		}
	}

	public static String findLabelContent(String label) {
		if (label == null) {
			return "unknown label";
		}
		if (map == null) {
			return "map is null";
		}
		String content = map.get(label);
		if (content == null || content.isEmpty()) {
			content = label;
		}
		return content;
	}

	/**
	 * Copy an existing file.
	 *
	 * @param service      Drive API service instance.
	 * @param originFileId ID of the origin file to copy.
	 * @param copyTitle    Title of the copy.
	 * @return The copied file if successful, {@code null} otherwise.
	 */
	public static File copyFile(Drive service, String originFileId, String copyName, String generatedFolderId)
			throws Exception {
		mLog.warn("entering copyFile");

		try {
			File copiedFile = new File();
			mLog.info("copiedFile instance");
			copiedFile.setName(copyName);
			copiedFile.setDescription(copyName);
			mLog.info("setname");
			// destinate folder
			copiedFile.setParents(Collections.singletonList(generatedFolderId));
			mLog.info("copiedFile.setParents");
			mLog.info("originFileId [" + originFileId + "]");
			File newFile = service.files().copy(originFileId, copiedFile).execute();
			if (newFile == null) {
				mLog.error("file is null");
				throw new Exception("file is null");
			}
			mLog.info("newFile id [" + newFile.getId() + "]");
			mLog.warn("exiting copyFile");
			return newFile;
		} catch (IOException e) {
			mLog.error("ERROR cannot find file " + e.getMessage());
			mLog.warn(" exiting copyFile");
			throw new Exception(e);
		}

	}
    /*
     * 
     */
	public static List<String> getSlidesExcluded(Iterable<WizardData> dataPages, Map<String, String> commentKeys) {
		mLog.warn("entering getSlidesExcluded comments");
	
		List<String> pageList = new ArrayList<String>();
		List<String> pageListToExclude = new ArrayList<String>();
		// get all pages

		for (WizardData data : dataPages) {

			// pull of data model
			PageNameEnum pageName = null;
			try {
				pageName = PageNameEnum.valueOf(data.getPagename());
				mLog.trace("page Name = " + pageName.toString());
				
				if (pageName == PageNameEnum.ConfidentialClientEvaluationOnePage) {
					pageList.add("ConfidentialClientEvaluationProposed");
				}
				
				if (pageName == PageNameEnum.TargetMarketingPage) {
					mLog.info("FOUND targetMaring page");
					
					pageList.add("TargetMarketingWant12to18ToWant19to25");
					pageList.add("TargetMarketingWant19to25ToWant26to35");
					pageList.add("TargetMarketingWant26to35ToWant36to45");
					pageList.add("TargetMarketingWant36to45ToWant46to55");
					pageList.add("TargetMarketingWant46to55ToWant55Plus");
				} else {
				pageList.add(pageName.toString());
				}
				
				
				
			} catch (Exception ex) {
				StringWriter sw = new StringWriter();
				PrintWriter pw = new PrintWriter(sw);
				ex.printStackTrace(pw);
				// mLog.error(ex);
				mLog.error("ERROR getSlidesExcluded [" + sw.toString() + "]");
				//mLog.error("error " + ex.getMessage());
				continue;
			}
			// get targetMarking data

		} // end of for loop

		// loop thru google slides
		if (!pageList.isEmpty()) {
			for (String slidename : commentKeys.keySet()) {
				//mLog.trace("google slide name " + slidename);
				if (!pageList.contains(slidename)) {
					//get slide id
					String slideId = commentKeys.get(slidename);
					mLog.warn("slide Id " + slideId);
					mLog.warn("slidename to remove " + slidename);
					pageListToExclude.add(slidename);
				}

			}
		}
		mLog.warn("leaving exta getSlidesExcluded");
		return pageListToExclude;
	}

	/**
	 * 
	 * @param dataPages
	 * @return pages that are execluded
	 */
	public static List<String> getSlidesExcluded(Iterable<WizardData> dataPages) {
		mLog.warn("entering getSlidesExcluded");
		List<String> slidesList = new ArrayList<String>();
		// get all pages

		for (WizardData data : dataPages) {

			// pull of data model
			PageNameEnum pageName = null;
			try {
				pageName = PageNameEnum.valueOf(data.getPagename());
			} catch (Exception ex) {
				mLog.error("error " + ex.getMessage());
				continue;
			}
			// get targetMarking data
			if (pageName == PageNameEnum.TargetMarketingPage) {
				mLog.info("FOUND targetMaring page");
				List<String> targetList = new ArrayList<String>();
				targetList.add("TargetMarketingWant12to18ToWant19to25");
				targetList.add("TargetMarketingWant19to25ToWant26to35");
				targetList.add("TargetMarketingWant26to35ToWant36to45");
				targetList.add("TargetMarketingWant36to45ToWant46to55");
				targetList.add("TargetMarketingWant46to55ToWant55Plus");

				TargetMarketingPageModel targetMarketingPageModel = null;

				targetMarketingPageModel = (TargetMarketingPageModel) JSONManager.convertFromJson(data.getPagedata(),
						TargetMarketingPageModel.class);
				// model.addAttribute("targetMarketingPageModel", targetMarketingPageModel);
				TargetMarketingHeaderRow targetMarketingHeaderRow = new TargetMarketingHeaderRow(
						targetMarketingPageModel);
				String rowStatus = targetMarketingHeaderRow.getRowStatus();
				mLog.info("Row Status [" + rowStatus + "]");

				switch (rowStatus) {
				case "Want12to18ToWant19to25":
					targetList.remove("TargetMarketingWant12to18ToWant19to25");
					break;
				case "Want19to25ToWant26to35":
					targetList.remove("TargetMarketingWant19to25ToWant26to35");
					break;
				case "Want26to35ToWant36to45":
					targetList.remove("TargetMarketingWant26to35ToWant36to45");
					break;
				case "Want36to45ToWant46to55":
					targetList.remove("TargetMarketingWant36to45ToWant46to55");
					break;
				case "Want46to55ToWant55Plus":
					targetList.remove("TargetMarketingWant46to55ToWant55Plus");
					break;
				}// end of switch
					// loop thru list to add to removal
				for (String targetPage : targetList) {
					mLog.info("removing [" + targetPage + "]");
					slidesList.add(targetPage);
				}
			}

			// exculded
			if (data.isExcluded()) {
				mLog.info("PAGE Excluded id = " + pageName);
				mLog.info("PAGE Excluded name = [" + data.getPagename() + "]");
				slidesList.add(data.getPagename());
				continue;
			}
		} // end of for loop
		mLog.warn("leaving getSlidesExcluded");
		return slidesList;
	}

	/**
	 * 
	 * @param dataPages
	 * @return collection of pages
	 */
	public static List<SlideInterface> getSlidesData(Iterable<WizardData> dataPages) {
		mLog.warn("entering getSlidesData");
		List<SlideInterface> slidesList = new ArrayList<SlideInterface>();
		SlidesData slidesData = new SlidesData();

		PageModels pageModels = new PageModels();
		Publish publish = new Publish();
		// get all pages

		for (WizardData data : dataPages) {
			// pull of data model
			PageNameEnum pageName = null;
			try {
				pageName = PageNameEnum.valueOf(data.getPagename());
			} catch (Exception ex) {
				mLog.error("error " + ex.getMessage());
				continue;
			}

			// exculded
			if (data.isExcluded()) {
				mLog.info("PAGE Excluded name = " + pageName);
				continue;
			}
			switch (pageName) {

			// ConfidentialClientEvaluationOnePage
			case ClientObjectivesOnePage:
				try {

					ClientObjectivesOnePageModel clientObjectivesOnePageModel = null;
					clientObjectivesOnePageModel = (ClientObjectivesOnePageModel) JSONManager
							.convertFromJson(data.getPagedata(), ClientObjectivesOnePageModel.class);
					List<ClientObjectivesOnePageTwoModel> orderList = ClientObjectivesPageHelper.getList(true,
							clientObjectivesOnePageModel);

					List<Object> pageData = new ArrayList<Object>();
					pageData.add(clientObjectivesOnePageModel);
					pageData.add(orderList);

					slidesData.getPageModels().setOrderList(orderList);
					slidesData.getPageModels().setClientObjectivesOnePageModel(clientObjectivesOnePageModel);
					FourClientObjectiveSlide slideProductService = new FourClientObjectiveSlide(
							"StrategicMarketing_Data_PRODUCT_SERVICE!B1:E", "StrategicMarketing_Data_PRODUCT_SERVICE",
							SlideEnum.ClientObjectivePRODUCTSERVICE, slidesData);
					slidesList.add(slideProductService);
					FourClientObjectiveSlide slideConsumer = new FourClientObjectiveSlide(
							"StrategicMarketing_Data_CONSUMER!B1:E", "StrategicMarketing_Data_CONSUMER",
							SlideEnum.ClientObjectiveCONSUMER, slidesData);
					slidesList.add(slideConsumer);
					FourClientObjectiveSlide slidePromotion = new FourClientObjectiveSlide(
							"StrategicMarketing_Data_Promotion!B1:E", "StrategicMarketing_Data_Promotion",
							SlideEnum.ClientObjectivePROMOTION, slidesData);
					slidesList.add(slidePromotion);
					FourClientObjectiveSlide slideBrand = new FourClientObjectiveSlide(
							"StrategicMarketing_Data_Brand!A1:B", "StrategicMarketing_Data_Brand",
							SlideEnum.ClientObjectiveBRAND, slidesData);
					slidesList.add(slideBrand);

					FourClientObjectiveSlide slideTop = new FourClientObjectiveSlide("Strategic_Marketing_top!A1:E",
							"Strategic_Marketing_top", SlideEnum.ClientObjectiveTop, slidesData);
					slidesList.add(slideTop);

					mLog.info("found page ClientObjectivesOnePageTwoModel");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

			case ConfidentialClientEvaluationOnePage:
				try {
					ConfidentialClientEvaluationOnePageModel confidentialClientEvaluationOnePageModel = null;

					confidentialClientEvaluationOnePageModel = (ConfidentialClientEvaluationOnePageModel) JSONManager
							.convertFromJson(data.getPagedata(), ConfidentialClientEvaluationOnePageModel.class);
					List<PieChart> pieChart = ChartBuilder
							.buildLastYearConfidentialClientEvaluation(confidentialClientEvaluationOnePageModel);
					// slide 8
					slidesData.getPageModels()
					.setPieChartConfidentialClientEvaluationOnePage(pieChart);
					
					slidesData.getPageModels()
							.setConfidentialClientEvaluationOnePageModel(confidentialClientEvaluationOnePageModel);
					slidesData.getPublish().setConfidentialClientEvaluationOnePage(true);
					EightConfidentialClientEvaluationOneSlide slideEightConfidentialClientEvaluationOneSlide = new EightConfidentialClientEvaluationOneSlide(
							pieChart, "ConfidentialClientEvaluationOnePage_Data!A1:B",
							"ConfidentialClientEvaluationOnePage", SlideEnum.PieChart);

					slidesList.add(slideEightConfidentialClientEvaluationOneSlide);

					SevenConfidentialClientEvaluationTextSlide sevenConfidentialClientEvaluationTextSlide = new SevenConfidentialClientEvaluationTextSlide(
							slidesData, SlideEnum.TextSlideReplacement,"sevenConfidentialClientEvaluationOnePage");
					slidesList.add(sevenConfidentialClientEvaluationTextSlide);
					
					EightConfidentialClientEvaluationOneTextSlide eightConfidentialClientEvaluationOneTextSlide = new EightConfidentialClientEvaluationOneTextSlide(
							slidesData, SlideEnum.TextSlideReplacement,"EightConfidentialClientEvaluationOneTextSlide");
					slidesList.add(eightConfidentialClientEvaluationOneTextSlide);
					
					// model.addAttribute("ConfidentialClientEvaluationOnePageLastYearChartModel",
					// pieChart);
					// model.addAttribute("ConfidentialClientEvaluationOnePageModel", pieChart);
					// model.addAttribute("ConfidentialClientEvaluationPageDataModel",
					// confidentialClientEvaluationOnePageModel);

					if (pieChart.size() > 0) {
						publish.setConfidentialClientEvaluationOnePage(true);
					}

					// confidentialClientEvaluationProposedPage
					List<PieChart> pieChartProposed = ChartBuilder
							.buildNextYearConfidentialClientEvaluation(confidentialClientEvaluationOnePageModel);
					slidesData.getPageModels()
					.setPieChartConfidentialClientEvaluationProposed(pieChartProposed);
					// slide 9
					slidesData.getPublish().setConfidentialClientEvaluationProposedPage(true);
					NineConfidentialClientEvaluationProposedSlide nineConfidentialClientEvaluationProposedSlide = new NineConfidentialClientEvaluationProposedSlide(
							pieChartProposed, "ConfidentialClientEvaluationProposedPage_Data!A1:B",
							"ConfidentialClientEvaluationProposed", SlideEnum.PieChart);

					slidesList.add(nineConfidentialClientEvaluationProposedSlide);

					NineConfidentialClientEvaluationProposedTextSlide nineConfidentialClientEvaluation = new NineConfidentialClientEvaluationProposedTextSlide(slidesData, SlideEnum.TextSlideReplacement,"NineConfidentialClientEvaluationProposedTextSlide") ;
					slidesList.add(nineConfidentialClientEvaluation);
					
					// NineConfidentialClientEvaluationProposedSlide

					// model.addAttribute("ConfidentialClientEvaluationOnePageLastYearChartProposedModel",
					// pieChartProposed);
					// model.addAttribute("ConfidentialClientEvaluationOnePageModel",
					// pieChartProposed);

					if (pieChartProposed.size() > 0) {
						publish.setConfidentialClientEvaluationProposedPage(true);
					}

					mLog.info("found page ConfidentialClientEvaluationOnePageModel");
					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case CreateConceptOnePage:
				try {
					ExtraPageModel createConceptOnePageModel = null;

					createConceptOnePageModel = (ExtraPageModel) JSONManager.convertFromJson(data.getPagedata(),
							ExtraPageModel.class);
					// model.addAttribute("CreateConceptOnePageModel", createConceptOnePageModel);

					publish.setCreateConceptOnePage(true);
					mLog.info("found page createConceptOnePageModel");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case CreateConceptTwoPage:
				try {
					ExtraPageModel createConceptTwoPageModel = null;

					createConceptTwoPageModel = (ExtraPageModel) JSONManager.convertFromJson(data.getPagedata(),
							ExtraPageModel.class);
					// model.addAttribute("CreateConceptTwoPageModel", createConceptTwoPageModel);

					publish.setCreateConceptTwoPage(true);
					mLog.info("found page createConceptTwoPageModel");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case DigitalMobileSocialStrategiesPage:
				try {
					ExtraPageModel digitalMobileSocialStrategiesPageModel = null;

					digitalMobileSocialStrategiesPageModel = (ExtraPageModel) JSONManager
							.convertFromJson(data.getPagedata(), ExtraPageModel.class);
					// model.addAttribute("DigitalMobileSocialStrategiesPageModel",
					// digitalMobileSocialStrategiesPageModel);
					mLog.info("found page digitalMobileSocialStrategiesPage");

					publish.setDigitalMobileSocialStrategiesPage(true);

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

			case MarketPlaceCompetitionPage:
				try {
					MarketPlaceCompetitionPageModel marketPlaceCompetitionPageModel = null;

					marketPlaceCompetitionPageModel = (MarketPlaceCompetitionPageModel) JSONManager
							.convertFromJson(data.getPagedata(), MarketPlaceCompetitionPageModel.class);
					// model.addAttribute("MarketPlaceCompetitionPageModel",
					// marketPlaceCompetitionPageModel);
					slidesData.getPageModels().setMarketPlaceCompetitionPageModel(marketPlaceCompetitionPageModel);
					ThreeMarketPlaceCompetitionSlide slide = new ThreeMarketPlaceCompetitionSlide(slidesData,
							SlideEnum.TextSlideReplacement,"ThreeMarketPlaceCompetitionSlide");
					slidesList.add(slide);
					mLog.info("found page marketingStrategiesPageModel");

					publish.setMarketingStrategiesPage(true);
					publish.setMarketPlaceCompetitionPage(true);
					mLog.info("found page MarketPlaceCompetitionPageModel");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case MarketingStrategiesPage:
				try {
					ExtraPageModel marketingStrategiesPageModel = null;

					marketingStrategiesPageModel = (ExtraPageModel) JSONManager.convertFromJson(data.getPagedata(),
							ExtraPageModel.class);
					// model.addAttribute("MarketingStrategiesPageModel",
					// marketingStrategiesPageModel);

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

			case PlanABEPPage:
				try {
					PlanABEPPageModel planABEPPageModel = null;

					planABEPPageModel = (PlanABEPPageModel) JSONManager.convertFromJson(data.getPagedata(),
							PlanABEPPageModel.class);
					// model.addAttribute("PlanABEPPageModel", planABEPPageModel);
					slidesData.getPublish().setPlanABEPPage(true);
					slidesData.getPageModels().setPlanABEPPageModel(planABEPPageModel);
					TwentyPlanABEPTextSlide twentyPlanABEPTextSlide = new TwentyPlanABEPTextSlide(slidesData,
							SlideEnum.TextSlideReplacement, "TwentyPlanABEPTextSlide");
					slidesList.add(twentyPlanABEPTextSlide);

					// TwentyPlanABEPTextSlide
					mLog.info("found page PlanABEPPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

			case PlanADigitalROICalculatorPage:
				try {
					PlanDigitalROICalculatorPageModel planADigitalROICalculatorPageModel = null;

					planADigitalROICalculatorPageModel = (PlanDigitalROICalculatorPageModel) JSONManager
							.convertFromJson(data.getPagedata(), PlanDigitalROICalculatorPageModel.class);
					// model.addAttribute("PlanADigitalROICalculatorPage",
					// planADigitalROICalculatorPageModel);

					slidesData.getPublish().setPlanADigitalROICalculatorPage(true);

					slidesData.getPageModels()
							.setPlanADigitalROICalculatorPageModel(planADigitalROICalculatorPageModel);
					TwentyTwoPlanADigitalROICalculatorTextSlide textSlide = new TwentyTwoPlanADigitalROICalculatorTextSlide(
							slidesData, SlideEnum.TextSlideReplacement, "TwentyTwoPlanADigitalROICalculatorTextSlide");
					slidesList.add(textSlide);
					mLog.info("found page PlanADigitalROICalculatorPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

			case PlanAExcelPage:
				try {
					ExtraPageModel planAExcelPageModel = null;

					planAExcelPageModel = (ExtraPageModel) JSONManager.convertFromJson(data.getPagedata(),
							ExtraPageModel.class);
					String textArea = planAExcelPageModel.getTextArea();
					textArea = textArea.replaceAll("\\r\\n", "");
					// mLog.info("text planAExcelPageModel [" + textArea + "]");
					// planAExcelPageModel.setTextArea(textArea);
					// model.addAttribute("PlanAExcelPageModel", planAExcelPageModel);

					publish.setPlanAExcelPage(true);
					mLog.info("found page planAExcelPageModel");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case PlanAProposedPage:
				try {
					PlanProposedPageModel planAProposedPageModel = null;

					planAProposedPageModel = (PlanProposedPageModel) JSONManager.convertFromJson(data.getPagedata(),
							PlanProposedPageModel.class);
					// model.addAttribute("PlanAProposedPageModel", planAProposedPageModel);

					publish.setPlanAProposedPage(true);
					slidesData.getPublish().setPlanAProposedPage(true);
					slidesData.getPageModels().setPlanAProposedPageModel(planAProposedPageModel);
					NineteenPlanAProposedTextSlide nineteenPlanAProposedTextSlide = new NineteenPlanAProposedTextSlide(
							slidesData, SlideEnum.TextSlideReplacement,"NineteenPlanAProposedTextSlide");
					slidesList.add(nineteenPlanAProposedTextSlide);
					mLog.info("found page planAProposedPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case PlanBProposedPage:
				try {
					PlanProposedPageModel planBProposedPageModel = null;

					planBProposedPageModel = (PlanProposedPageModel) JSONManager.convertFromJson(data.getPagedata(),
							PlanProposedPageModel.class);
					// model.addAttribute("PlanBProposedPageModel", planBProposedPageModel);
					slidesData.getPublish().setPlanAProposedPage(true);
					slidesData.getPageModels().setPlanBProposedPageModel(planBProposedPageModel);
					TwentyFivePlanBProposedTextSlide twentyFivePlanAProposedTextSlide = new TwentyFivePlanBProposedTextSlide(
							slidesData, SlideEnum.TextSlideReplacement,"TwentyFivePlanBProposedTextSlide");
					slidesList.add(twentyFivePlanAProposedTextSlide);
					// publish.setPlanBProposedPage(true);
					mLog.info("found page planBProposedPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case PlanALifetimeValuedPage:
				try {
					PlanALifetimeValuedPageModel planALifetimeValuedPageModel = null;

					planALifetimeValuedPageModel = (PlanALifetimeValuedPageModel) JSONManager
							.convertFromJson(data.getPagedata(), PlanALifetimeValuedPageModel.class);
					// model.addAttribute("PlanALifetimeValuedPageModel",
					// planALifetimeValuedPageModel);

					slidesData.getPageModels().setPlanALifetimeValuedPageModel(planALifetimeValuedPageModel);
					TwentyOnePlanALifetimeValuedTextSlide textSlide = new TwentyOnePlanALifetimeValuedTextSlide(
							slidesData, SlideEnum.TextSlideReplacement,"TwentyOnePlanALifetimeValuedTextSlide");
					slidesList.add(textSlide);
					mLog.info("found page PlanALifetimeValuedPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

//PlanBDigitalROICalculatorPage

				//
			case PlanBLifetimeValuedPage:
				try {
					PlanBLifetimeValuedPageModel planBLifetimeValuedPageModel = null;

					planBLifetimeValuedPageModel = (PlanBLifetimeValuedPageModel) JSONManager
							.convertFromJson(data.getPagedata(), PlanBLifetimeValuedPageModel.class);
					// model.addAttribute("PlanBLifetimeValuedPageModel",
					// planBLifetimeValuedPageModel);
					slidesData.getPageModels().setPlanBLifetimeValuedPageModel(planBLifetimeValuedPageModel);
					TwentySevenPlanBLifetimeValuedTextSlide textSlide = new TwentySevenPlanBLifetimeValuedTextSlide(
							slidesData, SlideEnum.TextSlideReplacement,"TwentySevenPlanBLifetimeValuedTextSlide");
					slidesList.add(textSlide);
					mLog.info("found page PlanBLifetimeValuedPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
				//
			case PlanBExcelPage:
				try {
					ExtraPageModel planBExcelPagePageModel = null;

					planBExcelPagePageModel = (ExtraPageModel) JSONManager.convertFromJson(data.getPagedata(),
							ExtraPageModel.class);
					// model.addAttribute("PlanBExcelPageModel", planBExcelPagePageModel);

					mLog.info("found page PlanAExcelPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case PlanBBEPPage:
				try {
					PlanBBEPPageModel planBBEPPageModel = null;

					planBBEPPageModel = (PlanBBEPPageModel) JSONManager.convertFromJson(data.getPagedata(),
							PlanBBEPPageModel.class);
					// model.addAttribute("PlanBBEPPageModel", planBBEPPageModel);
					// slidesData.getPublish().setPlanBBEPPageModel(true);
					slidesData.getPageModels().setPlanBBEPPageModel(planBBEPPageModel);
					TwentySixPlanBBEPTextSlide twentySixPlanBBEPTextSlide = new TwentySixPlanBBEPTextSlide(slidesData,
							SlideEnum.TextSlideReplacement,"TwentySixPlanBBEPTextSlide");
					slidesList.add(twentySixPlanBBEPTextSlide);
					slidesData.getPublish().setPlanBBEPPage(true);
					mLog.info("found page PlanBBEPPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case PlanBDigitalROICalculatorPage:
				try {
					PlanDigitalROICalculatorPageModel planBDigitalROICalculatorPageModel = null;

					planBDigitalROICalculatorPageModel = (PlanDigitalROICalculatorPageModel) JSONManager
							.convertFromJson(data.getPagedata(), PlanDigitalROICalculatorPageModel.class);
					// model.addAttribute("PlanBDigitalROICalculatorPage",
					// planBDigitalROICalculatorPageModel);

					slidesData.getPublish().setPlanBDigitalROICalculatorPage(true);

					slidesData.getPageModels()
							.setPlanBDigitalROICalculatorPageModel(planBDigitalROICalculatorPageModel);
					TwentyEightPlanBDigitalROICalculatorTextSlide textSlide = new TwentyEightPlanBDigitalROICalculatorTextSlide(
							slidesData, SlideEnum.TextSlideReplacement,"TwentyEightPlanBDigitalROICalculatorTextSlide");
					slidesList.add(textSlide);

					publish.setPlanBDigitalROICalculatorPage(true);
					mLog.info("found page PlanBDigitalROICalculatorPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case PlanAMediaPage:
				mLog.info("found page PlanAMediaPage");
				try {
					PlanMediaPageModel planAMediaPagedataPageModel = null;
					planAMediaPagedataPageModel = (PlanMediaPageModel) JSONManager.convertFromJson(data.getPagedata(),
							PlanMediaPageModel.class);
					MediaChart mediaChartA = MediaChartHelper.generate(planAMediaPagedataPageModel);
					// model.addAttribute("PlanAMediaPage", mediaChartA);
					// model.addAttribute("PlanAMediaPagedataPageModel",
					// planAMediaPagedataPageModel);
					if (mediaChartA != null) {

						publish.setPlanAMediaPage(true);

						slidesData.getPublish().setPlanAMediaPage(true);
						slidesData.getPageModels().setPlanAMediaPagedataPageModel(planAMediaPagedataPageModel);
						SeventeenPlanAMediaSlide seventeenPlanAMediaSlide = new SeventeenPlanAMediaSlide(mediaChartA,
								"PlanAMediaPage_Data!A1:E", "PlanAMediaPage", SlideEnum.BarChart);
						slidesList.add(seventeenPlanAMediaSlide);
						TwentyNinePlanASpreadSheetSlide twentyNinePlanASpreadSheetSlide = new TwentyNinePlanASpreadSheetSlide(
								"PlanASpreadSheet!A1:P", "PlanASpreadSheet", SlideEnum.PlanASpreadSheet, slidesData);
						TwentyNinePlanASpreadSheetTextSlide twentyNinePlanASpreadSheetTextSlide = new TwentyNinePlanASpreadSheetTextSlide(
								slidesData, SlideEnum.TextSlideReplacement,"TwentyNinePlanASpreadSheetTextSlide");

						slidesList.add(twentyNinePlanASpreadSheetTextSlide);

						slidesList.add(twentyNinePlanASpreadSheetSlide);
						mLog.info("found page SeventeenPlanAMediaSlide");

					}
					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

				// PlanAProposedPage
			case PlanBMediaPage:
				mLog.info("found page PlanBMediaPage");
				try {
					PlanMediaPageModel planBMediaPagedataPageModel = null;
					planBMediaPagedataPageModel = (PlanMediaPageModel) JSONManager.convertFromJson(data.getPagedata(),
							PlanMediaPageModel.class);
					MediaChart mediaChart = MediaChartHelper.generate(planBMediaPagedataPageModel);
					// model.addAttribute("PlanBMediaPagedataPageModel",
					// planBMediaPagedataPageModel);
					// model.addAttribute("PlanBMediaPage", mediaChart);
					if (mediaChart != null) {

						publish.setPlanBMediaPage(true);
						slidesData.getPageModels().setPlanBMediaPagedataPageModel(planBMediaPagedataPageModel);
						slidesData.getPublish().setPlanBMediaPage(true);
						TwentyThreePlanBMediaSlide twentyThreePlanBMediaSlide = new TwentyThreePlanBMediaSlide(
								mediaChart, "PlanBMediaPage_Data!A1:E", "PlanBMediaPage", SlideEnum.BarChart);
						slidesList.add(twentyThreePlanBMediaSlide);
						ThirtyPlanBSpreadSheetSlide thirtyPlanBSpreadSheetSlide = new ThirtyPlanBSpreadSheetSlide(
								"PlanBSpreadSheet!A1:P", "PlanBSpreadSheet", SlideEnum.PlanBSpreadSheet, slidesData);

						ThirtyPlanBSpreadSheetTextSlide thirtyPlanBSpreadSheetTextSlide = new ThirtyPlanBSpreadSheetTextSlide(
								slidesData, SlideEnum.TextSlideReplacement,"ThirtyPlanBSpreadSheetTextSlide");

						slidesList.add(thirtyPlanBSpreadSheetTextSlide);
						slidesList.add(thirtyPlanBSpreadSheetSlide);
						mLog.info("found page TwentyThreePlanBMediaSlide");
						mLog.info("found page TwentyThreePlanBMediaSlide");

					}
					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case PresentedToPage:
				try {
					PresentedToPageModel presentedToPageModel = null;

					presentedToPageModel = (PresentedToPageModel) JSONManager.convertFromJson(data.getPagedata(),
							PresentedToPageModel.class);
					// model.addAttribute("PresentedToPage", presentedToPageModel);
					slidesData.getPublish().setPresentedToPage(true);
					slidesData.getPageModels().setPresentedToPageModel(presentedToPageModel);
					//if (!presentedToPageModel.getClientBusinessName().isEmpty() && !presentedToPageModel.getClientContactName().isEmpty()) {
						OnePresentedToSlide presentedToSlide = new OnePresentedToSlide(slidesData,
								SlideEnum.TextSlideReplacement,"OnePresentedToSlide");
						slidesList.add(presentedToSlide);
						mLog.info("found page PresentedToPage");
					//}
					
					
					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

			case ProfileOfConsumersPage:
				try {
					ExtraPageModel profileOfConsumersPageModel = null;

					profileOfConsumersPageModel = (ExtraPageModel) JSONManager.convertFromJson(data.getPagedata(),
							ExtraPageModel.class);
					// model.addAttribute("ProfileOfConsumersPageModel",
					// profileOfConsumersPageModel);

					publish.setProfileOfConsumersPage(true);

					mLog.info("found page profileOfConsumersPageModel");
					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

			case StrategicMarketingPageOne:
				try {
					StrategicMarketingPageOneModel strategicMarketingPageOneModel = null;

					strategicMarketingPageOneModel = (StrategicMarketingPageOneModel) JSONManager
							.convertFromJson(data.getPagedata(), StrategicMarketingPageOneModel.class);
					// model.addAttribute("StrategicMarketingPageOne",
					// strategicMarketingPageOneModel);

					publish.setStrategicMarketingPageOne(true);
					slidesData.getPageModels().setStrategicMarketingPageOneModel(strategicMarketingPageOneModel);
					// FiveStrategicMarketingPageSlide
					FourClientObjectiveTextSlide fourClientObjectiveTextSlide = new FourClientObjectiveTextSlide(
							slidesData, SlideEnum.TextSlideReplacement,"FourClientObjectiveTextSlide");
					slidesList.add(fourClientObjectiveTextSlide);

					mLog.info("value found page StrategicMarketingPageOne "
							+ strategicMarketingPageOneModel.getYearsInBusiness());
					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case StrategicMarketingPageThree:
				try {
					StrategicMarketingPageThreeModel strategicMarketingPageThreeModel = null;

					strategicMarketingPageThreeModel = (StrategicMarketingPageThreeModel) JSONManager
							.convertFromJson(data.getPagedata(), StrategicMarketingPageThreeModel.class);
					// model.addAttribute("StrategicMarketingPageThree",
					// strategicMarketingPageThreeModel);

					StrategicMarketingHelper strategicMarketingHelper = new StrategicMarketingHelper(
							strategicMarketingPageThreeModel);
					// model.addAttribute("StrategicMarketingHelper", strategicMarketingHelper);
					slidesData.getPageModels().setStrategicMarketingPageThreeModel(strategicMarketingPageThreeModel);
					slidesData.getPageModels().setStrategicMarketingHelper(strategicMarketingHelper);
					FiveStrategicMarketingPageSlide fiveStrategicMarketingPageSlide = new FiveStrategicMarketingPageSlide(
							slidesData, SlideEnum.TextSlideReplacement,"FiveStrategicMarketingPageSlide");
					slidesList.add(fiveStrategicMarketingPageSlide);
					publish.setStrategicMarketingPageThree(true);
					mLog.info("found page StrategicMarketingPageThree");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case StrategicMarketingPageTwo:
				mLog.info("start StrategicMarketingPageTwo");

				try {
					StrategicMarketingPageTwoModel strategicMarketingPageTwoModel = null;

					strategicMarketingPageTwoModel = (StrategicMarketingPageTwoModel) JSONManager
							.convertFromJson(data.getPagedata(), StrategicMarketingPageTwoModel.class);
					// model.addAttribute("StrategicMarketingPageTwo",
					// strategicMarketingPageTwoModel);

					publish.setStrategicMarketingPageTwo(true);
					mLog.info("found page StrategicMarketingPageTwo");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			case TargetMarketingPage:
				try {
					TargetMarketingPageModel targetMarketingPageModel = null;

					targetMarketingPageModel = (TargetMarketingPageModel) JSONManager
							.convertFromJson(data.getPagedata(), TargetMarketingPageModel.class);
					// model.addAttribute("targetMarketingPageModel", targetMarketingPageModel);
					TargetMarketingHeaderRow targetMarketingHeaderRow = new TargetMarketingHeaderRow(
							targetMarketingPageModel);

					// model.addAttribute("targetMarketingHeaderRow", targetMarketingHeaderRow);

					publish.setTargetMarketingPage(true);

					slidesData.getPublish().setTargetMarketingPage(true);
					slidesData.getPageModels().setTargetMarketingPageModel(targetMarketingPageModel);
					slidesData.getPageModels().setTargetMarketingHeaderRow(targetMarketingHeaderRow);
					SixTargetMarketingSlide slide = new SixTargetMarketingSlide(slidesData,
							SlideEnum.TextSlideReplacement, "SixTargetMarketingSlide");
					slidesList.add(slide);

					mLog.info("found page targetMarketingPageModel");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}

			case TeamCommitmentPage:
				try {
					TeamCommitmentPageModel teamCommitmentPageModel = null;

					teamCommitmentPageModel = (TeamCommitmentPageModel) JSONManager.convertFromJson(data.getPagedata(),
							TeamCommitmentPageModel.class);
					// model.addAttribute("TeamCommitmentPage", teamCommitmentPageModel);

					slidesData.getPublish().setTeamCommitmentPage(true);
					slidesData.getPageModels().setTeamCommitmentPageModel(teamCommitmentPageModel);
					TwoTeamCommitmentSlide slide = new TwoTeamCommitmentSlide(slidesData,
							SlideEnum.TextSlideReplacement,"TwoTeamCommitmentSlide");
					slidesList.add(slide);
					mLog.info("found page TeamCommitmentPage");

					break;
				} catch (Exception ex) {
					mLog.error("error " + ex.getMessage());
					break;
				}
			}
			// model.addAttribute("PublishModel", publish);

		}
		// BatchUpdatePresentationRequest update = new BatchUpdatePresentationRequest();
		// update.setRequests(mRequests);
		// googleSlides.presentations().batchUpdate(prez.getPresentationId(),
		// update).execute();
		mLog.warn("leaving getSlidesData");
		return slidesList;
	}

}
